import React, { useState } from "react";
import Head from "next/head";
import Home from "@/views/Home/Home";
import Layout from "@/layout/layout";

export default function HomePage() {
  const [selectedButton, setSelectedButton] = useState<string>("home");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout
          selectedButton={selectedButton}
          setSelectedButton={setSelectedButton}
        >
          <Home
            selectedButton={selectedButton}
            setSelectedButton={setSelectedButton}
          />
        </Layout>
      </main>
    </>
  );
}
