import React, { useState } from "react";
import Head from "next/head";
import Home from "@/views/Home/Home";
import Layout from "@/layout/layout";

export default function HomePage() {
  const [selectedButton, setSelectedButton] = useState<string>("home");
  const [signIn, setSignIn] = useState(false);
  const [signUp, setSignUp] = useState(false);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout
          selectedButton={selectedButton}
          setSelectedButton={setSelectedButton}
          signIn={signIn}
          setSignIn={setSignIn}
          signUp={signUp}
          setSignUp={setSignUp}
        >
          <Home
            selectedButton={selectedButton}
            setSelectedButton={setSelectedButton}
            signIn={signIn}
            setSignIn={setSignIn}
            signUp={signUp}
            setSignUp={setSignUp}
          />
        </Layout>
      </main>
    </>
  );
}
